name: Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Python'un son s端r端m端n端 kullan

      - name: dependencies
        run:
          pip install mkdocs mkdocs-material

      - name: build site
        run: mkdocs gh-deploy --force --clean --message "Auto-deploy via GitHub Actions"
